version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: economize_mais
    restart: always
    environment:
      POSTGRES_USER: economize_mais
      POSTGRES_PASSWORD: MOA0|tP1en0si
      POSTGRES_DB: economize_mais
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
